# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zero/msgtest

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zero/msgtest

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zero/msgtest/CMakeFiles /home/zero/msgtest/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zero/msgtest/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named msgsub

# Build rule for target.
msgsub: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 msgsub
.PHONY : msgsub

# fast build rule for target.
msgsub/fast:
	$(MAKE) -f CMakeFiles/msgsub.dir/build.make CMakeFiles/msgsub.dir/build
.PHONY : msgsub/fast

#=============================================================================
# Target rules for targets named msgpub

# Build rule for target.
msgpub: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 msgpub
.PHONY : msgpub

# fast build rule for target.
msgpub/fast:
	$(MAKE) -f CMakeFiles/msgpub.dir/build.make CMakeFiles/msgpub.dir/build
.PHONY : msgpub/fast

#=============================================================================
# Target rules for targets named router

# Build rule for target.
router: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 router
.PHONY : router

# fast build rule for target.
router/fast:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/build
.PHONY : router/fast

MessagePublisher.o: MessagePublisher.cpp.o

.PHONY : MessagePublisher.o

# target to build an object file
MessagePublisher.cpp.o:
	$(MAKE) -f CMakeFiles/msgpub.dir/build.make CMakeFiles/msgpub.dir/MessagePublisher.cpp.o
.PHONY : MessagePublisher.cpp.o

MessagePublisher.i: MessagePublisher.cpp.i

.PHONY : MessagePublisher.i

# target to preprocess a source file
MessagePublisher.cpp.i:
	$(MAKE) -f CMakeFiles/msgpub.dir/build.make CMakeFiles/msgpub.dir/MessagePublisher.cpp.i
.PHONY : MessagePublisher.cpp.i

MessagePublisher.s: MessagePublisher.cpp.s

.PHONY : MessagePublisher.s

# target to generate assembly for a file
MessagePublisher.cpp.s:
	$(MAKE) -f CMakeFiles/msgpub.dir/build.make CMakeFiles/msgpub.dir/MessagePublisher.cpp.s
.PHONY : MessagePublisher.cpp.s

MessageRouter.o: MessageRouter.cpp.o

.PHONY : MessageRouter.o

# target to build an object file
MessageRouter.cpp.o:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/MessageRouter.cpp.o
.PHONY : MessageRouter.cpp.o

MessageRouter.i: MessageRouter.cpp.i

.PHONY : MessageRouter.i

# target to preprocess a source file
MessageRouter.cpp.i:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/MessageRouter.cpp.i
.PHONY : MessageRouter.cpp.i

MessageRouter.s: MessageRouter.cpp.s

.PHONY : MessageRouter.s

# target to generate assembly for a file
MessageRouter.cpp.s:
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/MessageRouter.cpp.s
.PHONY : MessageRouter.cpp.s

MessageSubscriber.o: MessageSubscriber.cpp.o

.PHONY : MessageSubscriber.o

# target to build an object file
MessageSubscriber.cpp.o:
	$(MAKE) -f CMakeFiles/msgsub.dir/build.make CMakeFiles/msgsub.dir/MessageSubscriber.cpp.o
.PHONY : MessageSubscriber.cpp.o

MessageSubscriber.i: MessageSubscriber.cpp.i

.PHONY : MessageSubscriber.i

# target to preprocess a source file
MessageSubscriber.cpp.i:
	$(MAKE) -f CMakeFiles/msgsub.dir/build.make CMakeFiles/msgsub.dir/MessageSubscriber.cpp.i
.PHONY : MessageSubscriber.cpp.i

MessageSubscriber.s: MessageSubscriber.cpp.s

.PHONY : MessageSubscriber.s

# target to generate assembly for a file
MessageSubscriber.cpp.s:
	$(MAKE) -f CMakeFiles/msgsub.dir/build.make CMakeFiles/msgsub.dir/MessageSubscriber.cpp.s
.PHONY : MessageSubscriber.cpp.s

fatal.o: fatal.cpp.o

.PHONY : fatal.o

# target to build an object file
fatal.cpp.o:
	$(MAKE) -f CMakeFiles/msgsub.dir/build.make CMakeFiles/msgsub.dir/fatal.cpp.o
	$(MAKE) -f CMakeFiles/msgpub.dir/build.make CMakeFiles/msgpub.dir/fatal.cpp.o
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/fatal.cpp.o
.PHONY : fatal.cpp.o

fatal.i: fatal.cpp.i

.PHONY : fatal.i

# target to preprocess a source file
fatal.cpp.i:
	$(MAKE) -f CMakeFiles/msgsub.dir/build.make CMakeFiles/msgsub.dir/fatal.cpp.i
	$(MAKE) -f CMakeFiles/msgpub.dir/build.make CMakeFiles/msgpub.dir/fatal.cpp.i
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/fatal.cpp.i
.PHONY : fatal.cpp.i

fatal.s: fatal.cpp.s

.PHONY : fatal.s

# target to generate assembly for a file
fatal.cpp.s:
	$(MAKE) -f CMakeFiles/msgsub.dir/build.make CMakeFiles/msgsub.dir/fatal.cpp.s
	$(MAKE) -f CMakeFiles/msgpub.dir/build.make CMakeFiles/msgpub.dir/fatal.cpp.s
	$(MAKE) -f CMakeFiles/router.dir/build.make CMakeFiles/router.dir/fatal.cpp.s
.PHONY : fatal.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... msgsub"
	@echo "... msgpub"
	@echo "... router"
	@echo "... MessagePublisher.o"
	@echo "... MessagePublisher.i"
	@echo "... MessagePublisher.s"
	@echo "... MessageRouter.o"
	@echo "... MessageRouter.i"
	@echo "... MessageRouter.s"
	@echo "... MessageSubscriber.o"
	@echo "... MessageSubscriber.i"
	@echo "... MessageSubscriber.s"
	@echo "... fatal.o"
	@echo "... fatal.i"
	@echo "... fatal.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

